# Generated by Django 2.0 on 2018-09-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180912_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='othersphoto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
