# Generated by Django 2.0 on 2018-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180912_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='delete',
            field=models.DateField(blank=True, null=True),
        ),
    ]
