# Generated by Django 2.0 on 2018-09-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.FileField(blank=True, default='https://bigriverequipment.com/wp-content/uploads/2017/10/no-photo-available.png', null=True, upload_to=''),
        ),
    ]
