# Generated by Django 2.0 on 2018-09-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180913_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
