# Generated by Django 2.0 on 2018-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180914_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(error_messages={'blank': 'A contact needs a first name.'}, max_length=150),
        ),
    ]
